# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-30 16:44
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180530_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='height_field',
            new_name='height_coverfield',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='width_field',
            new_name='height_profilefield',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, height_field='height_coverfield', null=True, upload_to=accounts.models.upload_location, width_field='width_coverfield'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width_coverfield',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='width_profilefield',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='height_profilefield', null=True, upload_to=accounts.models.upload_location, width_field='width_profilefield'),
        ),
    ]
