# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180531_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_coverfield',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_coverfield',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
