# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180601_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height_coverfield',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_profilefield',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_coverfield',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='width_profilefield',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
