# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180601_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateo',
            field=models.CharField(choices=[(('1', '1'), ('2', '2'))], max_length=1, null=True),
        ),
    ]
