# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-01 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_dateo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dateo',
        ),
    ]
