# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-02 17:47
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userprofile_dateo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='profile cropping'),
        ),
    ]
