# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-02 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_profile_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_cropping',
        ),
    ]
