# Generated by Django 2.0.6 on 2018-08-04 14:13

import accounts.models
from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180616_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, height_field='height_coverfield', null=True, upload_to=accounts.models.upload_location, width_field='width_coverfield'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, height_field='height_profilefield', null=True, upload_to=accounts.models.upload_location, width_field='width_profilefield'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
