# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0002_auto_20180221_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sculpt',
            old_name='content_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='sculpt',
            old_name='content_image',
            new_name='image',
        ),
    ]
