# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-03 13:03
from __future__ import unicode_literals

from django.db import migrations
import sculpts.models
import sculpts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0007_auto_20180303_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpt',
            name='content',
            field=sculpts.models.NonStrippingTextField(validators=[sculpts.validators.validate_content]),
        ),
    ]
