# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0008_auto_20180303_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sculpt',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sculpt',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
