# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-07 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import sculpts.models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0009_auto_20180305_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpt',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=sculpts.models.upload_location, width_field='width_field'),
        ),
    ]
