# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sculpt',
            old_name='content',
            new_name='content_text',
        ),
        migrations.AddField(
            model_name='sculpt',
            name='content_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sculpt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sculpt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
