# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 09:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sculpts', '0003_auto_20180221_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
