# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import sculpts.models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0004_sculpt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpt',
            name='content',
            field=models.TextField(validators=[sculpts.models.validate_content]),
        ),
    ]
