# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import sculpts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0006_auto_20180303_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpt',
            name='content',
            field=models.TextField(validators=[sculpts.validators.validate_content]),
        ),
    ]
