# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-29 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0010_auto_20180307_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sculpt',
            options={'ordering': ['-timestamp']},
        ),
    ]
