# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-09 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sculpts', '0012_sculpt_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
