# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0013_sculpt_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Is a reply?'),
        ),
    ]
