# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0014_sculpt_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured aah? haha'),
        ),
    ]
