# Generated by Django 2.0.6 on 2018-06-16 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sculpts', '0015_sculpt_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sculpt',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sculpts.Sculpt'),
        ),
        migrations.AlterField(
            model_name='sculpt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
