# Generated by Django 2.0.6 on 2018-06-27 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sculpts', '0016_auto_20180616_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='sculpt',
            name='reported',
            field=models.ManyToManyField(blank=True, related_name='reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
